### ISSUE TITLE
Extend slidewinder to be able to produce slides for other frameworks. 

### ISSUE THREAD

**Issue by TransGirlCodes** [Blahah/slidewinder#8]
I would love to be able to use slidewinder to build slidedecks from collections that are for impress.js, and other HTML/JS presentation frameworks. Defining the content of a slide once in a collection, and having it useable from any kind of presentation framework, would be incredibly awesome!

I don't think this would be too difficult at all! Reading the source, and structure of this project. I _think_ the main things to do are add a handlebars HTML template to the package. And make sure that extra data attributes used by impress.js can be parsed from the YAML of the slides if necessary, and a command line option added to specify the presentation framework you want to use.

I'm willing to do work towards this, as it's something I'd love to use for the Cambs talk, and it looks at first glance like an easy bit of work.

What do you think?

**Comment by blahah** [comment]
I think this is an excellent idea and is another nice example of why having the slides as an independent collection from the presentation tool is a powerful paradigm. I made a `templates` directory as preparation for this scenario.

The steps to make this work are roughly:
- add a barebones impress.js deck as an HTML file to the templates directory
- edit the template so that it has the `{{slidewinder}}` handlebar template placeholder for the slides in the correct place
- do some refactoring so that the app can run preprocessors for certain templates
- write a preprocessor to convert the raw slide markdown to whatever impress.js wants
- add the command-line option to choose the presentation framework

**Comment by blahah** [comment]
If you wanted to start a PR for this, I'm happy to help with code and/or guidance.

**Comment by blahah** [comment]
Implemented in PR #9 by @Ward9250

**Comment by blahah** [comment]
This issue was moved to slidewinder/slidewinder#8
